### ISSUE TITLE
Documentation required on how to run without the built-in chirpstack server

### ISSUE THREAD

**Issue by proffalken** [Argeniss-Software/rolaguard#6]
**Describe the bug**

First of all, this is an amazing project, thank you so much for releasing it!

It would be great to know exactly which of the docker containers are needed for a "production" deployment of the tool, i.e. one without the built-in chirpstack.

For example, are RabbitMQ and Postgresql part of rolaguard, or are they only required for Chirpstack?

I'm happy to help write this up if you can point me in the right direction!

**To Reproduce**

N/A

**Expected behavior**

Documentation exists to help deploy this somewhere other than docker-compose with Chirpstack.

**Screenshots**

N/A

**Comment by cpfarher** [comment]
Hello, first of all thank you for testing RolaGuard. We appreciate your comments!
It is worth to mention that there isn’t any Chirpstack running in the docker-compose, what you see is only a pre-configured open Chirpstack data source that we found on the Internet. Hence, all the components running are 100% necessary.
You can remove this data source and add more data sources by clicking on the Datasource option in the menu of the UI.
Don’t hesitate to contact us if you have any doubts or comments.

**Comment by proffalken** [comment]
Thanks, 

I've looked through the code and I can't see where that example stack is injected into the database?

When I ran this up earlier, even after I removed the demo source and added my own, I was seeing unexpected devices and gateways showing up, so it would be good to know how to disable the sample data!

**Comment by cyones** [comment]
Hi Matthew, thank you for your comments! To avoid the creation of this sample data source you can delete lines [88-89](https://github.com/Argeniss-Software/rolaguard_postgres/blob/ca1ee85899a7eddf30a97abe55f0b68113caea8c/2-data.sql#L88) of the file _2-data.sql_, in the project named _postgres_. Also, since you already have run the system and the database is already created, you should delete the folder _rolaguard_, created in your home directory.

**Comment by proffalken** [comment]
@cyones thanks, although neither that nor deleting the data source from the console appear to work, I ended up having to go into the database container and remove everything via the pgsql utility.

I'm going to give it a go deploying this using our existing PGSQL/RabbitMQ setup, is there anything I should be aware of in regard to running database migrations etc? (I'm assuming from the above scripts that auto-migrate is not enabled on this project?)

**Comment by cyones** [comment]
@proffalken, sorry, I forget an important step. After deleting those lines in the SQL file, you should rebuild the postgres docker image with
`docker build -t rolaguardcommunity/postgres:latest ./postgres`
Then you delete the database folder (created in _~/rolaguard_) and re-launch the whole system. 

Anyway, if you prefer to use your own database, you can use the scripts _1-schema.sql_ and _2-data.sql_ in the project postgres to create the schema and populate the database with the required data to launch the system. 

Besides this, you will need to modify the environment files [postgres.env](https://github.com/Argeniss-Software/rolaguard/blob/master/config/postgres.env) and [rabbitmq.env](https://github.com/Argeniss-Software/rolaguard/blob/master/config/rabbitmq.env) in the folder config to point to your services. [Here](https://docs.docker.com/network/) you have more information about how to access the host network from the docker network. Also, delete the postgres and rabbitmq sections in the [docker-compose.yml](https://github.com/Argeniss-Software/rolaguard/blob/master/docker-compose.yml) file (remember to delete them also from the dependencies of the other apps). Finally, if all works ok, you can launch the system using `docker-compose up`.

**Comment by proffalken** [comment]
Fantastic, thank you, I'll give that a go in the next few days.
